import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const rootUrl = new URL("../", import.meta.url);
const distUrl = new URL("dist/", rootUrl);
const assetsUrl = new URL("assets/", distUrl);
const sourceHtmlUrl = new URL("index.html", rootUrl);
const sourceRootUrl = new URL("src/", rootUrl);
const sourceEntryUrl = new URL("src/main.js", rootUrl);
const threeBoundaryUrl = new URL("src/platform/three.js", rootUrl);

const sourceHtml = await readFile(sourceHtmlUrl, "utf8");
const sourceEntry = await readFile(sourceEntryUrl, "utf8");
const threeBoundary = await readFile(threeBoundaryUrl, "utf8");

const threeModuleUrl = extractThreeModuleUrl(threeBoundary);
const bundleSource = createBundleSource(sourceEntry, threeModuleUrl);
const basePath = normalizeBasePath(process.env.BASE_PATH);
const assetPath = pathForBase(basePath, "assets/softskies.js");
const distHtml = createDistHtml(sourceHtml, basePath, assetPath);

await rm(distUrl, { recursive: true, force: true });
await mkdir(assetsUrl, { recursive: true });
await writeFile(new URL("index.html", distUrl), distHtml, "utf8");
await writeFile(new URL("softskies.js", assetsUrl), bundleSource, "utf8");
const copiedModules = await copySourceModules(sourceRootUrl, assetsUrl, { skip: new Set(["main.js"]) });
await writeFile(
  new URL("build-manifest.json", distUrl),
  `${JSON.stringify({
    sourceEntry: "src/main.js",
    bundle: "assets/softskies.js",
    copiedModules,
    basePath,
    externalModules: [threeModuleUrl],
  }, null, 2)}\n`,
  "utf8",
);

console.log(`Built ${path.relative(process.cwd(), new URL("index.html", distUrl).pathname)} with base path ${basePath}`);

function extractThreeModuleUrl(source) {
  const match = source.match(/export \* from ["'](?<url>https:\/\/[^"']+three[^"']+)["'];/);
  if (!match?.groups?.url) {
    throw new Error("Could not find the pinned Three.js module URL in src/platform/three.js.");
  }
  return match.groups.url;
}

async function copySourceModules(sourceDirUrl, outputDirUrl, { relativeDir = "", skip = new Set() } = {}) {
  const copied = [];
  const entries = await readdir(sourceDirUrl, { withFileTypes: true });

  for (const entry of entries) {
    const relativePath = path.posix.join(relativeDir, entry.name);
    const sourceUrl = new URL(`${entry.name}${entry.isDirectory() ? "/" : ""}`, sourceDirUrl);
    const outputUrl = new URL(`${entry.name}${entry.isDirectory() ? "/" : ""}`, outputDirUrl);

    if (entry.isDirectory()) {
      await mkdir(outputUrl, { recursive: true });
      copied.push(...await copySourceModules(sourceUrl, outputUrl, { relativeDir: relativePath, skip }));
      continue;
    }

    if (skip.has(relativePath)) {
      continue;
    }

    await writeFile(outputUrl, await readFile(sourceUrl, "utf8"), "utf8");
    copied.push(relativePath);
  }

  return copied.sort();
}

function createBundleSource(source, threeModuleUrl) {
  const importLine = 'import * as THREE from "./platform/three.js";';
  if (!source.includes(importLine)) {
    throw new Error(`Expected source entry to import Three.js through ${importLine}`);
  }

  return `// Generated by scripts/build.mjs. Do not edit dist/ output.\n${source.replace(importLine, `import * as THREE from "${threeModuleUrl}";`)}`;
}

function createDistHtml(html, basePath, assetPath) {
  const baseMeta = '<meta name="softskies-base-path" content="./" />';
  const sourceScript = '<script type="module" src="./src/main.js"></script>';
  if (!html.includes(baseMeta) || !html.includes(sourceScript)) {
    throw new Error("index.html no longer has the expected source entry markers for the build step.");
  }

  return html
    .replace(baseMeta, `<meta name="softskies-base-path" content="${escapeAttribute(basePath)}" />`)
    .replace(sourceScript, `<script type="module" src="${escapeAttribute(assetPath)}"></script>`);
}

function normalizeBasePath(rawBasePath) {
  if (!rawBasePath) {
    return "./";
  }

  const trimmed = rawBasePath.trim();
  if (trimmed === "" || trimmed === "." || trimmed === "./") {
    return "./";
  }

  return `/${trimmed.replace(/^\/+|\/+$/g, "")}/`;
}

function pathForBase(basePath, asset) {
  if (basePath === "./") {
    return `./${asset}`;
  }
  return `${basePath}${asset}`;
}

function escapeAttribute(value) {
  return value.replaceAll("&", "&amp;").replaceAll('"', "&quot;");
}
